# Exercicio 2

select * from DEPARTAMENTOS;

select PRIMEIRO_NOME, ULTIMO_NOME, DEPARTAMENTO_NOME, DEPARTAMENTOS.DEPARTAMENTO_ID
FROM EMPREGADOS, DEPARTAMENTOS
WHERE EMPREGADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.DEPARTAMENTO_ID
AND DEPARTAMENTOS.DEPARTAMENTO_NOME LIKE '%Financeiro%';
