-- Selecionar todas os EMPREGADOS que respondem para o GERENTE FINANCEIRO. Listar primeiro e último nome, e nome do gerente, e cargo de ambos.

SELECT
    EMPREGADO.PRIMEIRO_NOME, EMPREGADO.ULTIMO_NOME, DEPARTAMENTOS.DEPARTAMENTO_NOME, GERENTE.PRIMEIRO_NOME AS 'GERENTE'
FROM
    EMPREGADOS AS EMPREGADO, DEPARTAMENTOS, EMPREGADOS AS GERENTE
WHERE
    EMPREGADO.DEPARTAMENTO_ID = DEPARTAMENTOS.DEPARTAMENTO_ID
    AND DEPARTAMENTOS.DEPARTAMENTO_NOME LIKE '%Financeiro%'
    AND GERENTE.DEPARTAMENTO_ID = DEPARTAMENTOS.DEPARTAMENTO_ID
    AND EMPREGADO.GERENTE_ID = GERENTE.EMPREGADO_ID
    ;
    
