-- Selecionar todas os EMPREGADOS que respondem para o GERENTE FINANCEIRO. Listar primeiro e último nome, e nome do gerente, e cargo de ambos.

SELECT * FROM DEPARTAMENTOS;

SELECT
    PRIMEIRO_NOME, ULTIMO_NOME, DEPARTAMENTO_NOME, DEPARTAMENTOS.DEPARTAMENTO_ID
FROM
    EMPREGADOS, DEPARTAMENTOS
WHERE
    EMPREGADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.DEPARTAMENTO_ID
    AND     DEPARTAMENTOS.DEPARTAMENTO_NOME LIKE '%Financeiro%';
