# Exercicio 4


select PRIMEIRO_NOME as 'NOME', ULTIMO_NOME AS 'SOBRENOME', SALARIO 
from FUNCOES, EMPREGADOS
where EMPREGADOS.SALARIO >= FUNCOES.MAX_SALARIO 
OR EMPREGADOS.SALARIO <= FUNCOES.MIN_SALARIO

