-- Atualizar o salário de todos os EMPREGADOS que tem a função de PROGRAMADO, acrescendo 15% ao salário atual.

SELECT EMPREGADOS.SALARIO
FROM EMPREGADOS
WHERE EMPREGADOS.FUNCAO_ID = 'IT_PROG'
LIMIT 3 ;

UPDATE
    EMPREGADOS
SET
    EMPREGADOS.SALARIO = EMPREGADOS.SALARIO * 1.15
WHERE
    EMPREGADOS.FUNCAO_ID = 'IT_PROG'
    ;

SELECT EMPREGADOS.SALARIO
FROM EMPREGADOS
WHERE EMPREGADOS.FUNCAO_ID = 'IT_PROG'
LIMIT 3 ;
